import type { AnalysisResult, ReviewItem, ReviewStatus, SchoolLevel } from "./types";

type Rule = Omit<ReviewItem, "status" | "article" | "comment" | "current"> & { required: string[]; outdated?: string[]; schoolLevels?: SchoolLevel[] };
const src = {
  checklist: { label: "교육청 체크리스트", detail: "2026학년도 학교생활규정 제·개정 점검표 항목 우선 적용" },
  training: { label: "연수자료 PDF/PPT", detail: "2026학년도 학교규칙·학교생활규정 제·개정 컨설팅단 사전 연수자료" },
  law: { label: "초·중등교육법", detail: "학생생활지도, 개별학생교육지원, 스마트기기 사용 제한 등 관련 조항" },
  decree: { label: "초·중등교육법 시행령", detail: "학생생활지도 및 학칙 위임 사항 관련 조항" },
  notice: { label: "교원의 학생생활지도에 관한 고시", detail: "교육부고시 제2026-3호, 2026. 3. 1. 시행 기준" },
};
const RULES: Rule[] = [
  { id:"basis", checklistNo:"1", category:"총칙·근거", title:"적용근거와 고시 명칭 최신화", basis:"고시 연계", required:["초·중등교육법","교원의 학생생활지도에 관한 고시"], outdated:["2023-28"], sources:[src.checklist,src.training,src.law,src.decree,src.notice], revised:"제○조【적용근거】 이 규정은 「초·중등교육법」, 「초·중등교육법 시행령」, 「교원의 학생생활지도에 관한 고시」 등 관계 법령과 교육청 학교생활규정 제·개정 점검 기준에 따라 학생의 학교생활에 관한 사항을 정한다.", reason:"학교생활규정의 근거 조항은 최신 상위법, 시행령, 고시와 교육청 점검 기준을 함께 반영해야 합니다." },
  { id:"smart", checklistNo:"2", category:"스마트기기", title:"휴대전화 표현을 휴대전화 등 스마트기기로 정비", basis:"법령 연계", required:["스마트기기"], outdated:["휴대폰","통신기기"], sources:[src.checklist,src.law,src.notice,src.training], revised:"제○조【휴대전화 등 스마트기기 사용】 ① 학생은 수업 중 휴대전화 등 스마트기기를 사용해서는 안 된다. 다만, 장애 또는 특수교육 지원, 교육 목적, 긴급 상황 대응 등 학교의 장과 교원이 허용하는 경우에는 사용할 수 있다.\n② 학교의 장과 교원은 교육활동 보호와 학생의 학습권 보장을 위하여 필요한 경우 학칙과 학교생활규정이 정하는 바에 따라 휴대전화 등 스마트기기의 사용 제한 또는 분리 보관을 지도할 수 있다.", reason:"초·중등교육법 및 학생생활지도 고시 개정 흐름에 맞추어 휴대전화 중심 표현을 스마트기기 중심으로 정비해야 합니다." },
  { id:"support", checklistNo:"3", category:"개별학생교육지원", title:"기존 분리 조항을 개별학생교육지원 체계로 정비", basis:"법령 필수", required:["개별학생교육지원","학습지원"], outdated:["분리"], sources:[src.checklist,src.law,src.decree,src.notice,src.training], revised:"제○조【개별학생교육지원】 ① 학교의 장은 교육활동 보호와 학생의 학습권 보장을 위하여 개별학생교육지원이 필요하다고 판단하는 경우 그 장소, 시간, 학습지원 방법, 보호자 안내 절차를 정하여 운영할 수 있다.\n② 개별학생교육지원 중 학생에게 제공할 학습 과제, 상담, 보호자 인계 요청, 출결 처리 등 세부 사항은 관계 법령과 고시에 따라 운영한다.", reason:"2026. 3. 1. 시행 기준에서는 기존 분리 중심 표현을 개별학생교육지원의 장소·시간·학습지원 방법 등으로 구체화해야 합니다." },
  { id:"committee", checklistNo:"4", category:"학생선도·징계", title:"학생선도위원회 사전 통지 및 의견진술권 보장", basis:"법령 필수", required:["선도위원회","의견","보호자"], sources:[src.checklist,src.training,src.law,src.decree], revised:"제○조【학생선도위원회 절차】 ① 학교는 학생에 대한 징계 심의가 필요한 경우 학생 및 보호자에게 위원회 개최 일시, 장소, 사유, 의견진술 방법을 사전에 안내한다.\n② 학생 및 보호자에게 충분한 의견진술 기회를 부여하고, 불참 시 처리 방법을 사전에 고지한다.", reason:"학생 징계는 적법절차, 사전 통지, 학생 및 보호자의 의견진술 기회 보장이 핵심입니다." },
  { id:"objection", checklistNo:"5", category:"이의제기", title:"생활지도 및 개별학생교육지원 이의제기 절차 정비", basis:"고시 연계", required:["이의제기","14일"], sources:[src.checklist,src.notice,src.training], revised:"제○조【이의제기】 학생 또는 보호자는 생활지도 및 개별학생교육지원에 대하여 이의가 있는 경우 그 조치를 안 날부터 14일 이내에 학교의 장에게 이의를 제기할 수 있다. 학교의 장은 관계 법령과 학교 절차에 따라 그 처리 결과를 안내한다.", reason:"생활지도뿐 아니라 개별학생교육지원에 대한 이의제기 절차를 함께 확인해야 합니다." },
  { id:"items", checklistNo:"6", category:"소지품·물품보관", title:"소지 물품 조사와 분리 보관 절차 명확화", basis:"고시 연계", required:["소지","물품","보관"], sources:[src.checklist,src.notice,src.training], revised:"제○조【소지 물품 조사 및 분리 보관】 학교의 장과 교원은 학생과 교직원의 안전 및 교육활동 보호를 위하여 필요한 경우 관계 법령과 고시에 따라 학생 소지 물품을 확인하거나 분리 보관할 수 있다. 이 경우 목적, 방법, 보관 기간, 반환 절차를 학생에게 안내한다.", reason:"물품 조사와 보관은 학생 인권과 교육활동 보호가 함께 관련되므로 절차와 반환 기준이 명확해야 합니다." },
  { id:"revision", checklistNo:"7", category:"제·개정 절차", title:"학생·보호자·교원 의견수렴 및 학교운영위원회 심의", basis:"교육청 권고", required:["의견","학교운영위원회","공포"], sources:[src.checklist,src.training], revised:"제○조【학교생활규정 제·개정 절차】 학교는 학교생활규정을 제·개정할 때 학생, 보호자, 교원의 의견을 수렴하고 학교운영위원회 심의를 거쳐 학교장이 공포한다. 개정 내용은 학생과 보호자에게 안내한다.", reason:"학교생활규정은 교육공동체 의견수렴과 학교운영위원회 심의 절차를 통해 절차적 정당성을 확보해야 합니다." },
  { id:"expulsion", checklistNo:"고등-1", category:"학생선도·징계", title:"고등학교 퇴학처분 관련 절차 확인", basis:"법령 필수", required:["퇴학","재심"], schoolLevels:["고등학교"], sources:[src.checklist,src.law,src.decree,src.training], revised:"제○조【퇴학처분 절차】 고등학교에서 퇴학처분을 하는 경우 학생 및 보호자에게 사전 통지와 의견진술 기회를 부여하고, 진로상담, 재심 절차, 학습권 보호 방안을 안내한다.", reason:"퇴학처분은 고등학교에 한정되는 중대한 징계이므로 별도의 절차 보장이 필요합니다." }
];
function n(t:string){return t.replace(/\s+/g," ").trim();}
function findArticle(text:string, keys:string[]){const re=/(제\s*\d+\s*조[^\n]*)([\s\S]*?)(?=\n\s*제\s*\d+\s*조|$)/g;const arts=[...text.matchAll(re)].map(m=>n(`${m[1]} ${m[2]}`));const f=arts.find(a=>keys.some(k=>a.includes(k))); if(f) return f.slice(0,1000); const i=keys.map(k=>text.indexOf(k)).find(i=>i!==-1); return i!==undefined&&i>=0?n(text.slice(Math.max(0,i-250),i+750)):"관련 조항을 자동으로 찾지 못했습니다. 담당자 확인이 필요합니다.";}
function status(text:string, r:Rule): ReviewStatus {const req=r.required.every(k=>text.includes(k)); const old=r.outdated?.some(k=>text.includes(k))??false; if(req&&!old)return "적정"; if(req&&old)return "확인 필요"; return "보완 필요";}
function sum(items:ReviewItem[]){return{total:items.length,needsRevision:items.filter(i=>i.status==="보완 필요").length,needsReview:items.filter(i=>i.status==="확인 필요").length,adequate:items.filter(i=>i.status==="적정").length,notApplicable:items.filter(i=>i.status==="해당 없음").length};}
export function analyzeRegulation(p:{schoolName:string;schoolLevel:SchoolLevel;regulationText:string;checklistText?:string;regulationFileName?:string;checklistFileName?:string;}):AnalysisResult{const text=p.regulationText||"";const rules=RULES.filter(r=>!r.schoolLevels||r.schoolLevels.includes(p.schoolLevel));const items: ReviewItem[] = rules.map(r=>{const s: ReviewStatus = text.length<50?"확인 필요":status(text,r);return{id:r.id,checklistNo:r.checklistNo,status:s,category:r.category,title:r.title,article:"자동 추출",basis:r.basis,sources:r.sources,comment:s==="적정"?"관련 구조가 확인됩니다. 최종 문구는 학교 절차에 따라 확인하세요.":s==="확인 필요"?"관련 표현은 있으나 최신 용어 또는 절차와 혼재되어 확인이 필요합니다.":"체크리스트 및 근거 자료 기준으로 보완이 필요한 항목입니다.",current:text.length<50?"규정 본문이 충분히 입력되지 않았습니다.":findArticle(text,[...r.required,...(r.outdated??[])]),revised:r.revised,reason:r.reason};});return{schoolName:p.schoolName||"학교명 미입력",schoolLevel:p.schoolLevel,generatedAt:new Date().toISOString(),regulationFileName:p.regulationFileName,checklistFileName:p.checklistFileName,extractedTextLength:text.length,summary:sum(items),items,notice:"본 결과는 교육청 체크리스트, 연수자료, 초·중등교육법, 초·중등교육법 시행령, 교원의 학생생활지도에 관한 고시를 근거로 한 AI 검토 보조 결과입니다. 최종 개정안은 학교 절차에 따라 확정해야 합니다."};}
